INSERT INTO resource(id, name) VALUES (1, 'Prometheus')
INSERT INTO resource(id, name) VALUES (2, 'Promtail')
INSERT INTO resource(id, name) VALUES (3, 'Grafana')
INSERT INTO resource(id, name) VALUES (4, 'Jaeger')
INSERT INTO resource(id, name) VALUES (5, 'Loki')
INSERT INTO resource(id, name) VALUES (6, 'Elasticsearch')
INSERT INTO resource(id, name) VALUES (7, 'Logstash')
INSERT INTO resource(id, name) VALUES (8, 'kibana')